--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers (
    id integer NOT NULL,
    user_id integer NOT NULL,
    company_name character varying(255) NOT NULL,
    website character varying(255) NOT NULL,
    phone_number character varying(12) NOT NULL
);


ALTER TABLE public.employers OWNER TO postgres;

--
-- Name: employers_activations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers_activations (
    id integer NOT NULL,
    employer_id integer NOT NULL,
    is_email_confirmed boolean NOT NULL,
    is_employer_activated boolean NOT NULL
);


ALTER TABLE public.employers_activations OWNER TO postgres;

--
-- Name: employers_activations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employers_activations ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.employers_activations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999
    CACHE 1
);


--
-- Name: job_positions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_positions (
    id integer NOT NULL,
    job_title character varying(50) NOT NULL
);


ALTER TABLE public.job_positions OWNER TO postgres;

--
-- Name: job_positions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_positions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.job_positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999
    CACHE 1
);


--
-- Name: jobseekers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobseekers (
    id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying(35) NOT NULL,
    last_name character varying(35) NOT NULL,
    identity_number character varying(11) NOT NULL,
    birth_date date NOT NULL
);


ALTER TABLE public.jobseekers OWNER TO postgres;

--
-- Name: jobseekers_activations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobseekers_activations (
    id integer NOT NULL,
    jobseeker_id integer NOT NULL,
    is_email_confirmed boolean NOT NULL,
    is_mernis_valid boolean NOT NULL
);


ALTER TABLE public.jobseekers_activations OWNER TO postgres;

--
-- Name: jobseekers_activations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jobseekers_activations ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.jobseekers_activations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999
    CACHE 1
);


--
-- Name: system_personels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_personels (
    id integer NOT NULL,
    user_id integer NOT NULL,
    username character varying(35) NOT NULL
);


ALTER TABLE public.system_personels OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(320) NOT NULL,
    password character varying(25) NOT NULL,
    created_at date DEFAULT CURRENT_DATE NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employers pk_employers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT pk_employers PRIMARY KEY (id);


--
-- Name: employers_activations pk_employers_activations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_activations
    ADD CONSTRAINT pk_employers_activations PRIMARY KEY (id);


--
-- Name: job_positions pk_job_positions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_positions
    ADD CONSTRAINT pk_job_positions PRIMARY KEY (id);


--
-- Name: jobseekers pk_jobseekers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobseekers
    ADD CONSTRAINT pk_jobseekers PRIMARY KEY (id);


--
-- Name: jobseekers_activations pk_jobseekers_activations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobseekers_activations
    ADD CONSTRAINT pk_jobseekers_activations PRIMARY KEY (id);


--
-- Name: system_personels pk_system_personels; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_personels
    ADD CONSTRAINT pk_system_personels PRIMARY KEY (id);


--
-- Name: users pk_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT pk_users PRIMARY KEY (id);


--
-- Name: job_positions uc_job_positions_job_title; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_positions
    ADD CONSTRAINT uc_job_positions_job_title UNIQUE (job_title);


--
-- Name: jobseekers uc_jobseekers_identity_number; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobseekers
    ADD CONSTRAINT uc_jobseekers_identity_number UNIQUE (identity_number);


--
-- Name: users uc_users_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);


--
-- Name: employers_activations fk_employers_activations_employers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_activations
    ADD CONSTRAINT fk_employers_activations_employers FOREIGN KEY (employer_id) REFERENCES public.employers(id) ON DELETE CASCADE;


--
-- Name: employers fk_employers_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT fk_employers_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: jobseekers_activations fk_jobseekers_activations_jobseekers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobseekers_activations
    ADD CONSTRAINT fk_jobseekers_activations_jobseekers FOREIGN KEY (jobseeker_id) REFERENCES public.jobseekers(id) ON DELETE CASCADE;


--
-- Name: jobseekers fk_jobseekers_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobseekers
    ADD CONSTRAINT fk_jobseekers_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: system_personels fk_system_personels_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_personels
    ADD CONSTRAINT fk_system_personels_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

