-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cities
(
    city_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_name character varying NOT NULL,
    PRIMARY KEY (city_id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    company_name character varying(255) NOT NULL,
    website character varying(255) NOT NULL,
    phone_number character varying(12) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers_activations
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 999999 CACHE 1 ),
    employer_id integer NOT NULL,
    is_email_confirmed boolean NOT NULL,
    is_employer_activated boolean NOT NULL,
    is_employer_activated_from_admin boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_advertisements
(
    job_advertisement_id integer NOT NULL,
    employer_id integer NOT NULL,
    job_position_id integer NOT NULL,
    city_id integer NOT NULL,
    salary_min integer,
    salary_max integer,
    number_of_open_job_position character varying NOT NULL,
    application_deadline date NOT NULL,
    create_date date NOT NULL,
    active boolean NOT NULL,
    job_advertisement_description character varying,
    job_salary_max integer,
    job_salary_min integer,
    number_of_open_job_positions integer
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 999999 CACHE 1 ),
    job_title character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobseekers
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying(35) NOT NULL,
    last_name character varying(35) NOT NULL,
    identity_number character varying(11) NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobseekers_activations
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 999999 CACHE 1 ),
    jobseeker_id integer NOT NULL,
    is_email_confirmed boolean NOT NULL,
    is_mernis_valid boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_personels
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    username character varying(35) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(320) NOT NULL,
    password character varying(25) NOT NULL,
    created_at date NOT NULL,
    dtype character varying(31) NOT NULL,
    company_name character varying(255),
    phone_number character varying(255),
    website character varying(255),
    birth_date date,
    first_name character varying(255),
    identity_number character varying(255),
    last_name character varying(255),
    username character varying(255),
    PRIMARY KEY (id)
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
        REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers_activations
    ADD FOREIGN KEY (employer_id)
        REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (city_id)
        REFERENCES public.cities (city_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (employer_id)
        REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (job_position_id)
        REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (employer_id)
        REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY (user_id)
        REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobseekers_activations
    ADD FOREIGN KEY (jobseeker_id)
        REFERENCES public.jobseekers (id)
    NOT VALID;


ALTER TABLE public.system_personels
    ADD FOREIGN KEY (user_id)
        REFERENCES public.users (id)
    NOT VALID;

END;